# Generated by Django 6.0.2 on 2026-03-12 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbPedidosProdutos',
            fields=[
                ('id_pedido_produto', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_pedidos_produtos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbClientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('senha', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_clientes',
            },
        ),
        migrations.CreateModel(
            name='TbCupons',
            fields=[
                ('id_cupom', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_cupons',
            },
        ),
        migrations.CreateModel(
            name='TbProdutos',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('imagem', models.CharField(blank=True, max_length=255, null=True)),
                ('tempo_preparo', models.IntegerField(blank=True, null=True)),
                ('disponivel', models.BooleanField(blank=True, null=True)),
                ('destaque', models.BooleanField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_produtos',
            },
        ),
        migrations.CreateModel(
            name='TbRestaurantes',
            fields=[
                ('id_restaurante', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('avaliacao', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('tempo_entrega', models.CharField(blank=True, max_length=20, null=True)),
                ('taxa_entrega', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cupom', models.CharField(blank=True, max_length=50, null=True)),
                ('imagem', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('aberto', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tb_restaurantes',
            },
        ),
        migrations.CreateModel(
            name='TbStatusPedido',
            fields=[
                ('id_status', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tb_status_pedido',
            },
        ),
        migrations.CreateModel(
            name='TbFidelidade',
            fields=[
                ('id_fidelidade', models.AutoField(primary_key=True, serialize=False)),
                ('pontos', models.IntegerField(blank=True, null=True)),
                ('cashback', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(db_column='ID_cliente', on_delete=django.db.models.deletion.CASCADE, to='foodverse.tbclientes')),
            ],
            options={
                'db_table': 'tb_fidelidade',
            },
        ),
        migrations.CreateModel(
            name='TbPedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('data_pedido', models.DateTimeField(blank=True, null=True)),
                ('endereco_entrega', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(db_column='ID_cliente', on_delete=django.db.models.deletion.CASCADE, to='foodverse.tbclientes')),
                ('restaurante', models.ForeignKey(db_column='ID_restaurante', on_delete=django.db.models.deletion.CASCADE, to='foodverse.tbrestaurantes')),
                ('status', models.ForeignKey(db_column='status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodverse.tbstatuspedido')),
            ],
            options={
                'db_table': 'tb_pedidos',
            },
        ),
        migrations.CreateModel(
            name='TbPagamentos',
            fields=[
                ('id_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(db_column='ID_pedido', on_delete=django.db.models.deletion.CASCADE, to='foodverse.tbpedidos')),
            ],
            options={
                'db_table': 'tb_pagamentos',
            },
        ),
        migrations.CreateModel(
            name='TbNutricao',
            fields=[
                ('id_nutricao', models.AutoField(primary_key=True, serialize=False)),
                ('kcal', models.IntegerField(blank=True, null=True)),
                ('proteina', models.CharField(blank=True, max_length=20, null=True)),
                ('carbo', models.CharField(blank=True, max_length=20, null=True)),
                ('gordura', models.CharField(blank=True, max_length=20, null=True)),
                ('produto', models.ForeignKey(db_column='ID_produto', on_delete=django.db.models.deletion.CASCADE, to='foodverse.tbprodutos')),
            ],
            options={
                'db_table': 'tb_nutricao',
            },
        ),
        migrations.CreateModel(
            name='TbEstoque',
            fields=[
                ('id_estoque', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('estoque_minimo', models.IntegerField(blank=True, null=True)),
                ('ultima_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('produto', models.ForeignKey(db_column='ID_produto', on_delete=django.db.models.deletion.CASCADE, to='foodverse.tbprodutos')),
            ],
            options={
                'db_table': 'tb_estoque',
            },
        ),
        migrations.CreateModel(
            name='TbReservas',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('data_reserva', models.DateTimeField(blank=True, null=True)),
                ('numero_pessoas', models.IntegerField(blank=True, null=True)),
                ('mesa', models.CharField(blank=True, max_length=10, null=True)),
                ('cliente', models.ForeignKey(db_column='ID_cliente', on_delete=django.db.models.deletion.CASCADE, to='foodverse.tbclientes')),
                ('restaurante', models.ForeignKey(db_column='ID_restaurante', on_delete=django.db.models.deletion.CASCADE, to='foodverse.tbrestaurantes')),
            ],
            options={
                'db_table': 'tb_reservas',
            },
        ),
        migrations.AddField(
            model_name='tbprodutos',
            name='restaurante',
            field=models.ForeignKey(blank=True, db_column='ID_restaurante', null=True, on_delete=django.db.models.deletion.CASCADE, to='foodverse.tbrestaurantes'),
        ),
        migrations.CreateModel(
            name='TbFuncionarios',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('senha', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
                ('restaurante', models.ForeignKey(blank=True, db_column='ID_restaurante', null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodverse.tbrestaurantes')),
            ],
            options={
                'db_table': 'tb_funcionarios',
            },
        ),
        migrations.CreateModel(
            name='TbAvaliacoes',
            fields=[
                ('id_avaliacao', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('data_avaliacao', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(db_column='ID_cliente', on_delete=django.db.models.deletion.CASCADE, to='foodverse.tbclientes')),
                ('restaurante', models.ForeignKey(db_column='ID_restaurante', on_delete=django.db.models.deletion.CASCADE, to='foodverse.tbrestaurantes')),
            ],
            options={
                'db_table': 'tb_avaliacoes',
            },
        ),
    ]
