# Generated by Django 6.0.2 on 2026-03-18 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodverse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbAvaliacoesProdutos',
            fields=[
                ('id_avaliacao_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('data_avaliacao', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(db_column='ID_cliente', on_delete=django.db.models.deletion.CASCADE, to='foodverse.tbclientes')),
                ('produto', models.ForeignKey(db_column='ID_produto', on_delete=django.db.models.deletion.CASCADE, to='foodverse.tbprodutos')),
            ],
            options={
                'db_table': 'tb_avaliacoes_produtos',
            },
        ),
    ]
