# Generated by Django 6.0.2 on 2026-03-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodverse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbrestaurantes',
            name='banner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
