# Generated by Django 6.0.2 on 2026-03-19 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodverse', '0002_tbavaliacoesprodutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbestoque',
            name='unidade',
            field=models.CharField(blank=True, default='un', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tbestoque',
            name='estoque_minimo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tbestoque',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='TbMovimentacaoEstoque',
            fields=[
                ('id_movimentacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_movimento', models.DateTimeField(auto_now_add=True)),
                ('estoque', models.ForeignKey(db_column='ID_estoque', on_delete=django.db.models.deletion.CASCADE, to='foodverse.tbestoque')),
            ],
            options={
                'db_table': 'tb_movimentacao_estoque',
            },
        ),
        migrations.CreateModel(
            name='TbReceitas',
            fields=[
                ('id_receita', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidade', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('insumo', models.ForeignKey(db_column='ID_insumo', on_delete=django.db.models.deletion.CASCADE, related_name='receitas_insumo', to='foodverse.tbprodutos')),
                ('produto_venda', models.ForeignKey(db_column='ID_produto_venda', on_delete=django.db.models.deletion.CASCADE, related_name='receitas_produto_venda', to='foodverse.tbprodutos')),
            ],
            options={
                'db_table': 'tb_receitas',
            },
        ),
    ]
