# Generated by Django 6.0.2 on 2026-03-19 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodverse', '0003_tbestoque_unidade_alter_tbestoque_estoque_minimo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbreceitas',
            old_name='unidade',
            new_name='unidades',
        ),
    ]
