/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.senac.food.verse.gui;

import com.senac.food.verse.PedidoDAO;
import com.senac.food.verse.Pedidos;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.JLabel;

/**
 *
 * @author thiago.boliveira13
 */
public class EntregasPainel extends javax.swing.JPanel {

    private final PedidoDAO dao = new PedidoDAO();

    private JPanel jPanelCards;
    private JScrollPane JScrollPanel;
    private JLabel quantidadeEntregas;

    public EntregasPainel() {
        initCustomComponents();
        criarMenuEntregas();
        atualizarContadorEntregas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initCustomComponents() {
    setLayout(new BorderLayout());

    // Título e contador
    JPanel headerPanel = new JPanel();
    headerPanel.setLayout(new BoxLayout(headerPanel, BoxLayout.X_AXIS));
    JLabel lblTitulo = new JLabel("Entregas Prontas");
    lblTitulo.setFont(new Font("Arial", Font.BOLD, 16));
    lblTitulo.setForeground(new Color(40, 40, 40));
    quantidadeEntregas = new JLabel("0");
    quantidadeEntregas.setFont(new Font("Arial", Font.PLAIN, 16));
    quantidadeEntregas.setForeground(new Color(25, 135, 84));
    headerPanel.add(lblTitulo);
    headerPanel.add(Box.createHorizontalStrut(16));
    headerPanel.add(quantidadeEntregas);

    // Botão Recarregar
    JButton btnRecarregar = new JButton("Recarregar");
    btnRecarregar.setFont(new Font("Arial", Font.BOLD, 12));
    btnRecarregar.setBackground(new Color(100, 149, 237)); // azul clarinho
    btnRecarregar.setForeground(Color.WHITE);
    btnRecarregar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    btnRecarregar.setFocusPainted(false);
    btnRecarregar.addActionListener((ActionEvent e) -> {
        criarMenuEntregas();
        atualizarContadorEntregas();
    });

    headerPanel.add(Box.createHorizontalStrut(20)); // espaçamento
    headerPanel.add(btnRecarregar);

    add(headerPanel, BorderLayout.NORTH);

    // Cards
    jPanelCards = new JPanel();
    jPanelCards.setLayout(new BoxLayout(jPanelCards, BoxLayout.Y_AXIS));
    JScrollPanel = new JScrollPane(jPanelCards);
    JScrollPanel.setBorder(null);
    JScrollPanel.getVerticalScrollBar().setUnitIncrement(14);

    add(JScrollPanel, BorderLayout.CENTER);
}


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Cria os cards de entrega pronta (Delivery)
    public void criarMenuEntregas() {
        ArrayList<Pedidos> pedidos = dao.buscarTodosPedidos();
        jPanelCards.removeAll();

        int contador = 0;
        for (Pedidos pedido : pedidos) {
            if ("pronto".equalsIgnoreCase(pedido.getStatusPedido())
                    && "Delivery".equalsIgnoreCase(pedido.getModoEntrega())) {
                JPanel entregaCard = criarEntregaCard(pedido);
                jPanelCards.add(Box.createVerticalStrut(10));
                jPanelCards.add(entregaCard);
                contador++;
            }
        }
        quantidadeEntregas.setText(String.valueOf(contador));
        jPanelCards.revalidate();
        jPanelCards.repaint();
    }

    private JPanel criarEntregaCard(Pedidos pedido) {
        JPanel card = new JPanel();
        card.setLayout(new GroupLayout(card));
        card.setBackground(Color.WHITE);
        card.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        card.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        GroupLayout layout = (GroupLayout) card.getLayout();
        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);

        JLabel idLabel = new JLabel("#" + pedido.getIdPedido());
        idLabel.setFont(new Font("Arial", Font.BOLD, 13));
        idLabel.setForeground(new Color(60, 60, 60));

        JLabel clienteLabel = new JLabel(pedido.getNomeCliente());
        clienteLabel.setFont(new Font("Arial", Font.PLAIN, 13));
        clienteLabel.setForeground(new Color(100, 100, 100));

        JLabel enderecoLabel = new JLabel("<html><div style='width:180px'>"
                + pedido.getEnderecoCompleto() + "</div></html>");
        enderecoLabel.setFont(new Font("Arial", Font.PLAIN, 12));
        enderecoLabel.setForeground(new Color(80, 80, 80));

        JLabel statusLabel = new JLabel(pedido.getStatusPedido());
        statusLabel.setFont(new Font("Arial", Font.BOLD, 13));
        statusLabel.setForeground(new Color(25, 135, 84));
        statusLabel.setBorder(BorderFactory.createEmptyBorder(5, 0, 5, 0));
        statusLabel.setHorizontalAlignment(SwingConstants.RIGHT);

        JButton btnEntregar = new JButton("Marcar como Entregue");
        btnEntregar.setFont(new Font("Arial", Font.BOLD, 12));
        btnEntregar.setBackground(new Color(25, 135, 84));
        btnEntregar.setForeground(Color.WHITE);
        btnEntregar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        btnEntregar.addActionListener((ActionEvent e) -> {
            // Troca status do pedido para "finalizado"
            dao.atualizarStatusPedido(pedido.getIdPedido(), "finalizado"); // Você precisa implementar esse método!
            criarMenuEntregas();
            atualizarContadorEntregas();
        });

        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(idLabel)
                                .addGap(8)
                                .addComponent(clienteLabel)
                                .addGap(16)
                                .addComponent(enderecoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 0, Short.MAX_VALUE)
                                .addComponent(statusLabel)
                                .addGap(16)
                                .addComponent(btnEntregar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        )
        );
        layout.setVerticalGroup(
                layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.CENTER)
                                .addComponent(idLabel)
                                .addComponent(clienteLabel)
                                .addComponent(enderecoLabel)
                                .addComponent(statusLabel)
                                .addComponent(btnEntregar))
        );

        return card;
    }

    private void atualizarContadorEntregas() {
        int qtd = 0;
        ArrayList<Pedidos> pedidos = dao.buscarTodosPedidos();
        for (Pedidos pedido : pedidos) {
            if ("pronto".equalsIgnoreCase(pedido.getStatusPedido())
                    && "Delivery".equalsIgnoreCase(pedido.getModoEntrega())) {
                qtd++;  
            }
        }
        quantidadeEntregas.setText(String.valueOf(qtd));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
