package com.senac.food.verse.gui;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author josie
 */
public class PedidosPanel extends javax.swing.JPanel {

    /**
     * Creates new form PedidosPanel
     */
    public PedidosPanel() {
        initComponents();
        configurarTabela();
        carregarPedidos();
    }

    
    private void configurarTabela() {
        // Modelo de dados da tabela
        String[] colunas = {"Nº Pedido", "Mesa", "Itens", "Status", "Hora"};
        DefaultTableModel model = new DefaultTableModel(colunas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Torna a tabela não editável
            }
        };
        tabelaPedidos.setModel(model);
        
        // Configurar largura das colunas
        tabelaPedidos.getColumnModel().getColumn(0).setPreferredWidth(80);  // Nº Pedido
        tabelaPedidos.getColumnModel().getColumn(1).setPreferredWidth(60);   // Mesa
        tabelaPedidos.getColumnModel().getColumn(2).setPreferredWidth(200);  // Itens
        tabelaPedidos.getColumnModel().getColumn(3).setPreferredWidth(100);  // Status
        tabelaPedidos.getColumnModel().getColumn(4).setPreferredWidth(80);   // Hora
    }

    private void carregarPedidos() {
        // Exemplo com dados mockados - substituir por conexão com BD
        DefaultTableModel model = (DefaultTableModel) tabelaPedidos.getModel();
        model.setRowCount(0); // Limpa a tabela
        
        // Dados de exemplo
        model.addRow(new Object[]{"001", "Mesa 5", "2x Pizza, 1x Refri", "Preparando", "12:30"});
        model.addRow(new Object[]{"002", "Mesa 2", "1x Lasanha", "Aguardando", "12:45"});
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        btnNovoPedido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPedidos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDetalhesPedido = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnPronto = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Pedidos ativos");
        jPanel1.add(jLabel2);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtualizar);

        btnNovoPedido.setText("Novo Pedido");
        btnNovoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovoPedido);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tabelaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaPedidos);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        txtDetalhesPedido.setColumns(20);
        txtDetalhesPedido.setRows(5);
        jScrollPane2.setViewportView(txtDetalhesPedido);

        jPanel2.add(jScrollPane2);

        btnPronto.setText("Marcar como Pronto");
        btnPronto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProntoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar Pedido");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPronto)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(14, 14, 14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnPronto)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        carregarPedidos();

    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoPedidoActionPerformed
        JOptionPane.showMessageDialog(this, "Funcionalidade em desenvolvimento!");
    }//GEN-LAST:event_btnNovoPedidoActionPerformed

    private void btnProntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProntoActionPerformed
        int linhaSelecionada = tabelaPedidos.getSelectedRow();
        if(linhaSelecionada >= 0) {
            ((DefaultTableModel)tabelaPedidos.getModel())
                .setValueAt("Pronto", linhaSelecionada, 3);
        }
        
    }//GEN-LAST:event_btnProntoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnNovoPedido;
    private javax.swing.JButton btnPronto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaPedidos;
    private javax.swing.JTextArea txtDetalhesPedido;
    // End of variables declaration//GEN-END:variables
}
